name: test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.7', '3.0', '3.1', '3.2']
    services:
      fake-s3:
        image: lphoward/fake-s3
        ports:
          - 4569:4569
    env:  
      BUNDLE_PATH: vendor/bundler
    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - uses: actions/cache@v1
        id: cache
        with:
          path: vendor/bundler
          key: ${{ hashFiles('Gemfile.lock') }}-${{ matrix.ruby }}
      - run: |
          gem install bundler
          bundle install
          bundle exec rspec

